# target variable
target_variable: 
  name: 'NACCALZD' 
  map: {0: 0, 1: 1, 8: 0} #map the three classes variable to binary variable
test_size: 0.2 # test size
groups: 'NACCID'
k_fold: 4
random_state: 42 # random state
model_dict:
  {
    
    'gb': {
      'n_estimators': 200,
      'learning_rate': 0.05,
      'max_depth': 6,
      'min_samples_leaf': 50,
      'max_features': 0.3
    },
    
  }
preprocessing:
  drop_columns: ['NACCETPR', 'NACCALZP', 'PROBAD', 'PROBADIF', 'POSSAD', 'POSSADIF', 'NACCADMD']# drop columns
  missing_values_threshold: 0.2 # drop columns with more than 50% missing values
  normalize_method : 'min_max' # normalize method (min_max, z_score)
protected_attributes:
  RACE: 
    name: 'RACE'
    map: {
      'White': 1, 
      'black_or_African_American': 2,
      'American_Indian_or_Alaska_Native': 3,
      # 'Native_Hawaiian_or_Other_Pacific_Islander': 4,
      'Asian': 5
    }

  SEX: 
    name: 'SEX'
    map: {
      'Male': 1,
      'Female': 2
      }