target_variable: 'NACCALZD' # target variable
test_size: 0.2 # test size
random_state: 42 # random state
model_dict:
  {
    'lr': {
      'C': 100,
      'solver': 'saga'
    },
    'gb': {
      'n_estimators': 200,
      'learning_rate': 0.05,
      'max_depth': 6,
      'min_samples_leaf': 50,
      'max_features': 0.3
    },
    'rf': {
      'n_estimators': 200,
      'max_features': 'auto',
      'max_depth' : 6,
      'criterion' : 'entropy'
    },
    'svm': {
      'C': 100,
      'gamma': 0.01,
      'kernel': 'rbf'
    },
    'nn' :{
      'hidden_layer_sizes': [128,32],
      'activation': 'tanh',
      'solver': 'adam',
      'alpha': 0.05,
      'learning_rate': 'adaptive',
    }
  }
preprocessing:
  drop_columns: ['NACCETPR', 'NACCALZP', 'PROBAD', 'PROBADIF', 'POSSAD', 'POSSADIF', 'NACCADMD']# drop columns
  missing_values_threshold: 0.2 # drop columns with more than 50% missing values
  normalize_method : 'min_max' # normalize method (min_max, z_score)
protected_attributes:
  RACE: 
    name: 'RACE'
    map: {
      'White': 1, 
      'black_or_African_American': 2,
      'American_Indian_or_Alaska_Native': 3,
      # 'Native_Hawaiian_or_Other_Pacific_Islander': 4,
      'Asian': 5
    }

  SEX: 
    name: 'SEX'
    map: {
      'Male': 1,
      'Female': 2
      }